# Generated by Django 5.0 on 2026-03-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=5),
        ),
    ]
